SKILL_VOCAB = [
    "HTML",
    "CSS",
    "JavaScript",
    "TypeScript",
    "Vue",
    "React",
    "Node.js",
    "Python",
    "Java",
    "C++",
    "C",
    "Spring",
    "Spring Boot",
    "SQL",
    "MySQL",
    "Oracle",
    "MongoDB",
    "PostgreSQL",
    "Linux",
    "Docker",
    "Git",
    "Redis",
    "Kubernetes",
    "Nginx",
    "HTTP",
    "TCP/IP",
    "FastAPI",
    "Flask",
    "Django",
    "Selenium",
    "JMeter",
    "Postman",
    "PyTest",
    "Jenkins",
    "CI/CD",
    "接口测试",
    "自动化测试",
    "功能测试",
    "性能测试",
    "测试用例",
    "缺陷管理",
    "单片机",
    "PLC",
    "嵌入式",
    "硬件调试",
    "电路设计",
    "原型设计",
    "Axure",
    "PRD",
    "用户研究",
    "需求分析",
    "项目管理",
    "机器学习",
    "深度学习",
    "数据分析",
    "NLP",
    "LLM",
    # 新增：项目管理 / 售前 / 运营方向
    "商务谈判",
    "方案设计",
    "CRM",
    "ERP",
    "PMP",
    "PPT",
    "Word",
    "Excel",
    "Visio",
    "内容运营",
    "用户运营",
    "社区运营",
    "SEO",
    "pytest",
]

SKILL_ALIASES = {
    "Java": ["java", "java开发", "java 后端"],
    "Python": ["python", "py"],
    "JavaScript": ["javascript", "js"],
    "TypeScript": ["typescript", "ts"],
    "Vue": ["vue", "vue.js", "vue3"],
    "React": ["react", "react.js"],
    "Node.js": ["node", "nodejs", "node.js"],
    "C++": ["c++", "cpp", "c/c++"],
    "SQL": ["sql", "mysql sql", "sql语言"],
    "MySQL": ["mysql"],
    "Oracle": ["oracle"],
    "PostgreSQL": ["postgresql", "postgres"],
    "Spring": ["spring"],
    "Spring Boot": ["spring boot", "springboot"],
    "Git": ["git", "github", "gitlab"],
    "Linux": ["linux", "ubuntu", "centos"],
    "Redis": ["redis"],
    "Docker": ["docker", "容器化"],
    "Postman": ["postman", "接口调试"],
    "PyTest": ["pytest"],
    "JMeter": ["jmeter"],
    "Selenium": ["selenium"],
    "自动化测试": ["自动化测试", "ui自动化", "接口自动化"],
    "功能测试": ["功能测试"],
    "性能测试": ["性能测试", "压测"],
    "接口测试": ["接口测试", "api测试"],
    "项目管理": ["项目管理", "进度管理"],
    "需求分析": ["需求分析", "业务分析"],
    "原型设计": ["原型设计", "页面原型"],
    "Axure": ["axure"],
    "PRD": ["prd", "需求文档"],
    "数据分析": ["数据分析", "数据处理"],
    "LLM": ["llm", "大模型", "生成式ai"],
}

SOFT_SKILL_VOCAB = [
    "沟通",
    "团队协作",
    "学习能力",
    "抗压",
    "责任心",
    "执行力",
    "分析能力",
    "表达能力",
    # 赛题要求维度
    "创新",
    "服务意识",
    "客户关系",
]

SOFT_SKILL_ALIASES = {
    "沟通": ["沟通", "沟通能力", "客户沟通"],
    "团队协作": ["团队协作", "协作", "团队合作"],
    "学习能力": ["学习能力", "快速学习", "自学能力"],
    "抗压": ["抗压", "抗压能力"],
    "责任心": ["责任心"],
    "执行力": ["执行力", "落地能力"],
    "分析能力": ["分析能力", "问题分析"],
    "表达能力": ["表达能力", "汇报能力"],
    "创新": ["创新", "创新能力", "创新思维"],
    "服务意识": ["服务意识", "服务精神", "服务态度"],
    "客户关系": ["客户关系", "客户维护", "客户管理"],
}

CERTIFICATE_VOCAB = [
    "英语四级",
    "英语六级",
    "计算机二级",
    "软考",
    "PMP",
    "普通话证书",
]

EDUCATION_LEVELS = ["博士", "硕士", "本科", "大专"]

DEFAULT_GROWTH_PATHS = {
    "后端开发工程师": ["初级后端开发", "中级后端开发", "高级后端开发", "技术负责人"],
    "数据分析师": ["初级数据分析师", "数据分析师", "高级数据分析师", "数据产品经理"],
    "算法工程师": ["算法工程师", "高级算法工程师", "算法负责人", "AI 技术经理"],
}
